### ISSUE TITLE
Error with implode

### ISSUE THREAD

**Issue by rwal127** [nan-guo/Wordpress-ACF-Multi-Dates-Picker#2]
Hello, I am getting error after install your plugin:

> Warning: implode(): Invalid arguments passed in \wp-content\plugins\acf-multi-dates-picker\fields\class-pdg-acf-field-multi-dates-picker-v4.php on line 294

**WP** 4.9.4, **ACF** 4.4.11

All other functions works perfect! Thank's for your work!

**Comment by rwal127** [comment]
When I change line 294 to this, no errors at all: 

```
if (!empty($value)) {
            $value = implode(',', $value);
        }
```

**Comment by artursopelnik** [comment]
+1

`if( $value !== false ) {
		    $value = implode(',', $value);
        }`

**Comment by nan-guo** [comment]
Thank you very much !
